### ISSUE TITLE
Exception too generic

### ISSUE THREAD

**Issue by Adam314** [raphaelstolt/php-jsonpatch#3]
Hello
Great code. However the InvalidJsonException seems too generic for usage. If we have some REST API, then a client sends us the JSON-Patch document and we take some data from database, apply a patch and save it.

If client's JSON-Patch is invalid we should return HTTP code, like 400 Bad Request. But if our own json resource taken from database is invalid, then we should return soemthing like 501 Internal server error.

So it would be good to have two separate exceptions for invalid JSON-patch and invalid json document.

**Comment by raphaelstolt** [comment]
I guess the keywords here are *own json resource*, IMO it's not the responsibility of this library to guarantee valid JSON documents.
