### ISSUE TITLE
Immer path style mode

### ISSUE THREAD

**Issue by francislavoie** [raphaelstolt/php-jsonpatch#50]
[Immer](https://immerjs.github.io/immer/) is a super cool JS lib which helps with performing state mutations in frontend (or Node backends, I guess).

Immer [supports JSON patches](https://immerjs.github.io/immer/patches), but they have one small deviation; they define `path` as an array of strings instead of a `/` delimited string. This is slightly faster, because no string manipulation is necessary to `.split()` the string, and a loop can be used directly to navigate deeply.

It would be awesome if the PHP lib could support this style of `path` natively, to avoid some hackiness needed to convert the patches.

**Comment by raphaelstolt** [comment]
Added via 83edbd6a40e3feb6f8a687dfd6f342c0c1e9031a.

**Comment by francislavoie** [comment]
Awesome, thank you!
