### ISSUE TITLE
Throw an exception when trying to add element to nonexistent index?

### ISSUE THREAD

**Issue by smoskalenko** [raphaelstolt/php-jsonpatch#8]
Hi @raphaelstolt 

Thanks for your library, I think it's best library for patching JSONs on github ;) But we want to have another feature in our project - we want to catch the cases when someone trying to add element to array to nonexistent index, as example case with too large index in patch operation:

```
$inputArray = [
  'arrayField' => ['foo', 'bar', 'baz']
];

$jsonPatch = [
  ['op' => 'add', 'path' => '/arrayField/7', 'value' => 'new']
];
```

What are you thinking about throwing exception in such cases in [Rs/Json/Patch/Operations/Add::perform()](https://github.com/raphaelstolt/php-jsonpatch/blob/master/src/Rs/Json/Patch/Operations/Add.php#L66) method, so we can catch this and process as we want. Can I create pull request for this feature?

Best regards,
Slava

**Comment by raphaelstolt** [comment]
Hi @smoskalenko, how about performing a `test` operation prior to using one of the patch (i.e. `add`) methods?

**Comment by smoskalenko** [comment]
Hi @raphaelstolt 

Do you mean that before main patch request we should run test operation and check that array field contains specified index? 

Also I've played a little bit with test operation and found the following issue:

```php
$inputData =  json_encode( 
  [
    'arrayField' => [
        ['name' => 'foo'],
        ['name' => 'bar']
    ]
  ]
);
$jsonPatch = json_encode(
    [
        ['op' => 'test', 'path' => '/arrayField/0', 'value' => ["name" => "foo"]]
    ]
);

// Apply JSON patches
$patch = new Patch($inputData, $jsonPatch);
$patchedDocument = $patch->apply();
```

I get the *FailedTestException("Failed on Test PatchOperation at index: 0")*

It seems that new integration test is needed.

The basic issue is that in unit tests you instantiate the operation objects with the following structure (value is json encoded string, why?):
```php
$operation = new \stdClass;
$operation->path = '/chars/array';
$operation->value = '["abc", "def"]';

$testOperation = new Test($operation);
```

But in fact when we call patch() operations objects instantiate with stdObject where value also is stdObject in case of array (because of json_decode() make this).

```
object(stdClass)#239 (3) {
  ["op"]=>
  string(4) "test"
  ["path"]=>
  string(13) "/arrayField/0"
  ["value"]=>
  object(stdClass)#238 (1) {
    ["name"]=>
    string(3) "foo"
  }
}
```


P.S. In our application in most cases we have a big JSON documents, and patch request will consist of a several operations, so it's very comfortably just send PATCH request to REST API for-example and get the result - 200 OK , or 400 Bad Request
